# Generated by Django 2.1.3 on 2019-12-14 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('views', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='Voting',
            new_name='voting',
        ),
    ]
