# Generated by Django 3.0 on 2020-01-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('views', '0002_vote_voting'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeBD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Theme', models.BooleanField(default=False)),
            ],
        ),
    ]
