# Generated by Django 3.0 on 2019-12-28 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('views', '0003_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='isCheckbox',
            field=models.BooleanField(default=0),
        ),
    ]
